
import java.awt.Color;
import java.io.Serializable;
import java.net.MalformedURLException;
import java.net.URL;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import lib_rmi.IPlayer;
import lib_rmi.Player;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author __ntnc__
 */
public class MenuUser extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form MenuUser
     */
    IPlayer stub;
    GamePlayScreen screen;
//    Main m;
//    Main2 m2;

    public MenuUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        Thread t = new Thread(this);
        t.start();
//        this.add(screen);
        btnSave.setVisible(false);
        btnOpen.setVisible(false);
        this.setResizable(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        txtPlayerName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        radMedium = new javax.swing.JRadioButton();
        radHard = new javax.swing.JRadioButton();
        radEasy = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NTC's Program");

        jPanel1.setLayout(null);

        lblWelcome.setFont(new java.awt.Font(".VnMysticalH", 1, 36)); // NOI18N
        lblWelcome.setText("WELCOME TO BALL GAME !");
        jPanel1.add(lblWelcome);
        lblWelcome.setBounds(150, 30, 400, 40);
        jPanel1.add(txtPlayerName);
        txtPlayerName.setBounds(280, 80, 210, 29);

        jLabel4.setFont(new java.awt.Font(".VnMysticalH", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter your player's name here : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 80, 280, 30);

        btnStart.setFont(new java.awt.Font(".VnMysticalH", 1, 14)); // NOI18N
        btnStart.setText("Start new game");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        jPanel1.add(btnStart);
        btnStart.setBounds(280, 310, 150, 40);

        btnSave.setFont(new java.awt.Font(".VnMysticalH", 1, 12)); // NOI18N
        btnSave.setText("Save Result");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave);
        btnSave.setBounds(593, 380, 100, 30);

        btnOpen.setFont(new java.awt.Font(".VnMysticalH", 1, 14)); // NOI18N
        btnOpen.setText("View Rankings");
        btnOpen.setBorder(null);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        jPanel1.add(btnOpen);
        btnOpen.setBounds(580, 10, 120, 40);

        buttonGroup1.add(radMedium);
        radMedium.setFont(new java.awt.Font(".VnMysticalH", 0, 14)); // NOI18N
        radMedium.setText("Medium");
        jPanel1.add(radMedium);
        radMedium.setBounds(370, 160, 67, 23);

        buttonGroup1.add(radHard);
        radHard.setFont(new java.awt.Font(".VnMysticalH", 0, 14)); // NOI18N
        radHard.setText("Hard");
        jPanel1.add(radHard);
        radHard.setBounds(370, 190, 53, 23);

        buttonGroup1.add(radEasy);
        radEasy.setFont(new java.awt.Font(".VnMysticalH", 0, 14)); // NOI18N
        radEasy.setText("Easy");
        jPanel1.add(radEasy);
        radEasy.setBounds(370, 130, 55, 25);

        jLabel3.setFont(new java.awt.Font(".VnMysticalH", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Choose game's level :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 160, 230, 17);

        btnExit.setFont(new java.awt.Font(".VnMysticalH", 1, 14)); // NOI18N
        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(310, 370, 90, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 710, 440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        screen = new GamePlayScreen();
        screen.setVisible(true);
//        m=new Main();
//        m.setVisible(true);
//        m2=new Main2();
//        m2.setVisible(true);

        btnSave.setVisible(true);
        btnOpen.setVisible(true);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        TableRankings tr = new TableRankings(this, true);
        tr.setVisible(true);
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            Player p = new Player();
            p.setName(txtPlayerName.getText());
            p.setScore(screen.getScore());
            if (radEasy.isSelected()) {
                p.setLevel("Easy");
            }
            if (radHard.isSelected()) {
                p.setLevel("Hard");
            }
            if (radMedium.isSelected()) {
                p.setLevel("Medium");
            }
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDateTime now = LocalDateTime.now();
            p.setDatePlay(dtf.format(now));
            stub = (IPlayer) Naming.lookup("rmi://localhost:9999/ntnc");
            stub.insert(p);
        } catch (NotBoundException ex) {
            Logger.getLogger(MenuUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(MenuUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(MenuUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtPlayerName.setText("");
        JOptionPane.showMessageDialog(rootPane, "Your data have been recorded !");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnStart;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JRadioButton radEasy;
    private javax.swing.JRadioButton radHard;
    private javax.swing.JRadioButton radMedium;
    private javax.swing.JTextField txtPlayerName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            if (lblWelcome.getForeground() == Color.BLACK) {
                lblWelcome.setForeground(Color.red);
            } else if (lblWelcome.getForeground() == Color.red) {
                lblWelcome.setForeground(Color.orange);
            } else {
                lblWelcome.setForeground(Color.black);
            }
            try {
                Thread.sleep(500);
            } catch (InterruptedException ex) {
                Logger.getLogger(MenuUser.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
